M48
; DRILL file {KiCad 6.0.6-3a73a75311~116~ubuntu22.04.1} date Sat 06 Aug 2022 20:48:40 CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-06T20:48:40+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.6-3a73a75311~116~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X1.2598Y-1.9685
X2.6772Y-1.9685
T0
M30
