M48
; DRILL file {KiCad 6.0.8-f2edbf62ab~116~ubuntu22.04.1} date Fri 11 Nov 2022 11:19:36 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-11T11:19:36+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.8-f2edbf62ab~116~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X3.812Y-4.1535
X4.062Y-3.7205
T0
M30
