M48
; DRILL file {KiCad 6.0.11-2627ca5db0~126~ubuntu22.04.1} date Tue 28 Nov 2023 13:50:45 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-28T13:50:45+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11-2627ca5db0~126~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X1.2598Y-1.9685
X2.6772Y-1.9685
T0
M30
